# Generated by Django 2.1 on 2018-09-29 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(blank=True)),
                ('sprint_name', models.CharField(max_length=256)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Team')),
            ],
        ),
        migrations.CreateModel(
            name='RetrospectiveNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun', models.PositiveSmallIntegerField()),
                ('value', models.PositiveSmallIntegerField()),
                ('great', models.CharField(blank=True, max_length=512, null=True)),
                ('better', models.CharField(blank=True, max_length=512, null=True)),
                ('sprint_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrospectives.Retrospective')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AgileUser')),
            ],
        ),
        migrations.CreateModel(
            name='RetrospectiveUserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.CharField(choices=[('better', 'better'), ('great', 'great')], max_length=16)),
                ('votes', models.PositiveSmallIntegerField(default=1)),
                ('agile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AgileUser')),
                ('retrospective_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='retrospectives.RetrospectiveNumber')),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.BooleanField(default=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrospectives.RetrospectiveUserFeedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='retrospective',
            unique_together={('team', 'sprint_number')},
        ),
    ]
