# Generated by Django 2.1 on 2018-09-29 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('column', 'Column'), ('line', 'Line')], default='column', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='agileuser',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Team'),
        ),
        migrations.AddField(
            model_name='agileuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
